services:
  # Database
  db:
    image: postgres:13
    container_name: webkhambenh-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webkhambenh
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./webkhambenh.sql:/docker-entrypoint-initdb.d/webkhambenh.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webkhambenh-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d webkhambenh"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Auth Service
  auth-service:
    build: ./AuthService
    container_name: auth-service
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=webkhambenh
      - JWT_SECRET=haha
      - JWT_EXPIRES_IN=24h
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - webkhambenh-network

  # Doctor Service
  doctor-service:
    build: ./DsBsService
    container_name: doctor-service
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=webkhambenh
    ports:
      - "3002:3002"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - webkhambenh-network

  # Appointment Service
  appointment-service:
    build: ./DatLichService
    container_name: appointment-service
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=webkhambenh
    ports:
      - "3003:3003"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - webkhambenh-network

  # Frontend
  frontend:
    build: ./webkhambenh
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_AUTH_API_URL=http://localhost:3001/api
      - REACT_APP_DOCTOR_API_URL=http://localhost:3002/api
      - REACT_APP_APPOINTMENT_API_URL=http://localhost:3003/api
    depends_on:
      - auth-service
      - doctor-service
      - appointment-service
    networks:
      - webkhambenh-network

volumes:
  postgres_data:

networks:
  webkhambenh-network:
    driver: bridge 