services:
  # Database cho Kong
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    volumes:
      - kong_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Cổng PostgreSQL mặc định, dùng riêng cho Kong
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Database cho ứng dụng
  app-database:
    image: postgres:13
    container_name: app-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: webkhambenh
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - app_data:/var/lib/postgresql/data
      - ./webkhambenh.sql:/docker-entrypoint-initdb.d/webkhambenh.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Kong migration
  kong-migration:
    image: kong:3.4
    command: kong migrations up
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PG_DATABASE: kong
    depends_on:
      kong-database:
        condition: service_healthy

  # Kong API Gateway
  kong:
    image: kong:3.4
    container_name: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
    ports:
      - "8000:8000"  # Kong proxy port
      - "8001:8001"  # Kong admin API
      - "8443:8443"  # Kong proxy SSL port
    depends_on:
      - kong-migration

  # AuthService
  auth-service:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - DB_HOST=app-database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=
      - DB_NAME=webkhambenh
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      app-database:
        condition: service_healthy

  # DsBsService
  doctors-service:
    build:
      context: ./DsBsService
      dockerfile: Dockerfile
    container_name: doctors-service
    environment:
      - DB_HOST=app-database
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=
      - DB_NAME=webkhambenh
      - PORT=3002
    ports:
      - "3002:3002"
    depends_on:
      app-database:
        condition: service_healthy

  # Frontend
  frontend:
    build:
      context: ./webkhambenh
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - kong

volumes:
  kong_data:
  app_data: